os:
- linux
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip setuptools
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: danwos
  password:
    secure: PEKnJbNu0aaKJtAPkJ6pEi+kbYRjoaWsbqkZZnCUgGjkpyu9CyiLhXenhV6ogwjVqM9y2T5loO86brm3+ERLpXVPSuDbD9mhSwdoUv/yKdGjKdYvTnkLJXQHP2Kt/wAluhTEv5ik7anvIyUDxW+NNOjL3g1gxHYrcwLTDC9NsC7kuecmTD4gaHsNLcrAMrKdaXcM3r8IQXvqIRxk1C9tbANVTqz26B/r840fRac5JaOTHGrOnraIO+5rFKMB4hw+YFyrwEE/Ru6XYFFQ63VOI2WoXZdXTNVmHNUnK5Z7PsD0KNWecwyAuVjMqR2Mja/5J4Px9MR5tPtssaf7RXLY9AUU9aogOQhT3hOdQTTpZ6qeGlwcWpPEcLLPNbJaGMVgQRsrHuFs9wdUPi+EMORWUOpbaLQUj6Tz24AOdmGR2OwD8YCbabCAxKb9AOq9AOrV/PR6xOMzCd5s5sAED/EyBhjwMWD/C0EWxelkNNRXSttmcYaO0eeMvnUgrUymckpZD5CLcdOramuiTU9P+SY0Lq8BhvgiaI4HwLpLcbicqub9MJ7AZHlK5BchwBisx1QpqOBp09Y4SORgoMpD0mIZVApQf09k0X4ZqZ4reoTfAySCjIJQNFiMGUK84EW6gNZ0ltMzax+JKrbHZEMkx5a9BgLoyB+KOUqLtq5yRC07FQQ=
  on:
    tags: true
    branch: master
